# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movie.proto',
  package='movie',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmovie.proto\x12\x05movie\"!\n\x10\x46indMovieRequest\x12\r\n\x05query\x18\x01 \x01(\t\" \n\x0e\x46indMovieReply\x12\x0e\n\x06movies\x18\x01 \x03(\t2R\n\x10\x46indMovieService\x12>\n\nFindMovies\x12\x17.movie.FindMovieRequest\x1a\x15.movie.FindMovieReply\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FINDMOVIEREQUEST = _descriptor.Descriptor(
  name='FindMovieRequest',
  full_name='movie.FindMovieRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='movie.FindMovieRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=55,
)


_FINDMOVIEREPLY = _descriptor.Descriptor(
  name='FindMovieReply',
  full_name='movie.FindMovieReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='movies', full_name='movie.FindMovieReply.movies', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['FindMovieRequest'] = _FINDMOVIEREQUEST
DESCRIPTOR.message_types_by_name['FindMovieReply'] = _FINDMOVIEREPLY

FindMovieRequest = _reflection.GeneratedProtocolMessageType('FindMovieRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDMOVIEREQUEST,
  __module__ = 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.FindMovieRequest)
  ))
_sym_db.RegisterMessage(FindMovieRequest)

FindMovieReply = _reflection.GeneratedProtocolMessageType('FindMovieReply', (_message.Message,), dict(
  DESCRIPTOR = _FINDMOVIEREPLY,
  __module__ = 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.FindMovieReply)
  ))
_sym_db.RegisterMessage(FindMovieReply)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class FindMovieServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.FindMovies = channel.unary_unary(
          '/movie.FindMovieService/FindMovies',
          request_serializer=FindMovieRequest.SerializeToString,
          response_deserializer=FindMovieReply.FromString,
          )


  class FindMovieServiceServicer(object):

    def FindMovies(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_FindMovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'FindMovies': grpc.unary_unary_rpc_method_handler(
            servicer.FindMovies,
            request_deserializer=FindMovieRequest.FromString,
            response_serializer=FindMovieReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'movie.FindMovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaFindMovieServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def FindMovies(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaFindMovieServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def FindMovies(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    FindMovies.future = None


  def beta_create_FindMovieService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('movie.FindMovieService', 'FindMovies'): FindMovieRequest.FromString,
    }
    response_serializers = {
      ('movie.FindMovieService', 'FindMovies'): FindMovieReply.SerializeToString,
    }
    method_implementations = {
      ('movie.FindMovieService', 'FindMovies'): face_utilities.unary_unary_inline(servicer.FindMovies),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_FindMovieService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('movie.FindMovieService', 'FindMovies'): FindMovieRequest.SerializeToString,
    }
    response_deserializers = {
      ('movie.FindMovieService', 'FindMovies'): FindMovieReply.FromString,
    }
    cardinalities = {
      'FindMovies': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'movie.FindMovieService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
