# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import movie_pb2 as movie__pb2


class FindMovieServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FindMovies = channel.unary_unary(
        '/movie.FindMovieService/FindMovies',
        request_serializer=movie__pb2.FindMovieRequest.SerializeToString,
        response_deserializer=movie__pb2.FindMovieReply.FromString,
        )


class FindMovieServiceServicer(object):

  def FindMovies(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FindMovieServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FindMovies': grpc.unary_unary_rpc_method_handler(
          servicer.FindMovies,
          request_deserializer=movie__pb2.FindMovieRequest.FromString,
          response_serializer=movie__pb2.FindMovieReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'movie.FindMovieService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
